server:
  port: 15888
spring:
  application:
    name: paocai-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.12:8848
    sentinel:
      eager: true #取消Sentinel控制台懒加载
      transport:
        dashboard: 192.168.136.12:8858
  redis:
    host: 192.168.136.12
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      use-key-prefix: true #是否使用前缀
      key-prefix: CACHE_ #前缀
      cache-null-values: true #是否缓存空值，可以用去解决缓存穿透问题
# 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true #开启feign的熔断机制
logging:
  level:
    com.zyj.paocai: debug