server:
  port: 88
spring:
  application:
    name: paocai-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.12:8848
        namespace: ${spring.cloud.nacos.config.namespace}
        group: DEFAULT_GROUP
    sentinel:
      eager: true
      transport:
        dashboard: 192.168.136.12:8858
      filter:
        enabled: false
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
    gateway:
      routes:
        # 商品服务路由
        - id: product_route
          uri: lb://paocai-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: search_route
          uri: lb://paocai-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 会员服务路由
        - id: member_route
          uri: lb://paocai-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 优惠券服务路由
        - id: coupon_route
          uri: lb://paocai-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 订单服务路由
        - id: order_route
          uri: lb://paocai-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        # 库存服务路由
        - id: ware_route
          uri: lb://paocai-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: auth_route
          uri: lb://paocai-auth-server
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*),/$\{segment}
        - id: cart_route
          uri: lb://paocai-cart
          predicates:
            - Path=/api/cart/**
          filters:
            - RewritePath=/api/cart/(?<segment>.*),/$\{segment}
        - id: third_party_route
          uri: lb://paocai-thirdparty
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://paocai-manager
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/paocai-manager/$\{segment}

# 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'