server:
  port: 88
spring:
  application:
    name: paocai-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.12:8848
# 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'