server:
  port: 13888
spring:
  application:
    name: paocai-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.12:8848
  thymeleaf:
    cache: false
  redis:
    host: 192.168.136.12
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# elasticsearch
elasticsearch:
  hostname: 192.168.136.12
  port: 9200
management:
  endpoints:
    web:
      exposure:
        include: '*'
paocai:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10