server:
  port: 13888
spring:
  application:
    name: paocai-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.12:8848
    sentinel:
      eager: true #取消Sentinel控制台懒加载
      transport:
        dashboard: 192.168.136.12:8858
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
  redis:
    host: 192.168.136.12
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# elasticsearch
elasticsearch:
  hostname: 192.168.136.12
  port: 9200
# 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true #开启feign的熔断机制
paocai:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10