server:
  port: 9888
spring:
  application:
    name: paocai-order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.136.12:8848
        namespace: ${spring.cloud.nacos.config.namespace}
        group: DEFAULT_GROUP
    sentinel:
      eager: true #取消Sentinel控制台懒加载
      transport:
        dashboard: 192.168.136.12:8858
      datasource:
        flow:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-flow-rules
            groupId: SENTINEL_GROUP
            rule-type: flow
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.discovery.server-addr}
            dataId: ${spring.application.name}-degrade-rules
            groupId: SENTINEL_GROUP
            rule-type: degrade
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.136.12:3306/paocai_oms
      username: root
      password: root
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      #validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: 192.168.136.12
    port: 6379
  session:
    store-type: redis
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.136.12
    port: 5672
    virtual-host: /
    publisher-confirm-type: CORRELATED # 开启发送端确认
    publisher-returns: true # 开启发送端消息抵达队列的确认
    template:
      mandatory: true # 只要抵达队列，以异步发送优先回调我们这个returnConfirm
    listener:
      simple:
        acknowledge-mode: manual # 客户端手动确认收消息
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  # 主键位置
# 暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  sentinel:
    enabled: true #开启feign的熔断机制
paocai:
  thread:
    core-pool-size: 20
    maximum-pool-size: 200
    keep-alive-time: 10
# 支付宝支付
alipay:
  app_id: 2021000119617444
  notify_url: http://2bxi93.natappfree.cc/payed/notify
  return_url: http://member.gulimall.com/memberOrder.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do